
export const gyms = [
    { "id": 3, "location": "Huddinge" },
    { "id": 460, "location": "Kallhäll" },
    { "id": 461, "location": "Jakobsberg" },
    { "id": 524, "location": "Åkersberga" },
    { "id": 532, "location": "Haninge" },
    { "id": 6168, "location": "Lidingö" },
    { "id": 6169, "location": "Södertälje" },
    { "id": 6182, "location": "Häggvik" },
    { "id": 6223, "location": "Abrahamsberg" },
    { "id": 6225, "location": "Rålambshovsparken" },
    { "id": 6229, "location": "City" },
    { "id": 6230, "location": "Farsta" },
    { "id": 6231, "location": "Hagastan" },
    { "id": 6232, "location": "Hornstull" },
    { "id": 6233, "location": "Lindhagen" },
    { "id": 6235, "location": "Kungsholmen" },
    { "id": 6236, "location": "Orminge" },
    { "id": 6237, "location": "Ringen" },
    { "id": 6238, "location": "Sickla" },
    { "id": 6239, "location": "Skanstull" },
    { "id": 6241, "location": "Skrapan" },
    { "id": 6242, "location": "Solna" },
    { "id": 6243, "location": "Sundbyberg" },
    { "id": 6244, "location": "Sveavägen" },
    { "id": 16797, "location": "Barkarby" },
    { "id": 30924, "location": "Rotsunda" },
    { "id": 31668, "location": "Ekerö" },
];
